create table employee (
	id_employee INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	address VARCHAR(50),
	phone VARCHAR(50)
);
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (1, 'Melli', 'Brunini', 'mbrunini0@i2i.jp', 'Female', '3720 Gina Avenue', '650-715-7116');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (2, 'Nydia', 'Aplin', 'naplin1@vistaprint.com', 'Male', '15 Dayton Avenue', '393-848-7100');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (3, 'Jordon', 'Blagdon', 'jblagdon2@list-manage.com', 'Female', '2595 2nd Terrace', '675-130-6850');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (4, 'Hertha', 'Vickarman', 'hvickarman3@comsenz.com', 'Female', '4 Main Park', '659-707-1028');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (5, 'Jenna', 'Odger', 'jodger4@wsj.com', 'Female', '266 Fremont Place', '721-631-2776');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (6, 'Regan', 'Bugge', 'rbugge5@reference.com', 'Male', '2 Fairview Trail', '880-853-9359');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (7, 'Sidney', 'Joesbury', 'sjoesbury6@over-blog.com', 'Female', '8765 Merry Place', '991-799-0414');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (8, 'Alexine', 'Grishakov', 'agrishakov7@stumbleupon.com', 'Female', '09477 Laurel Point', '815-764-6122');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (9, 'Cesaro', 'Virgo', 'cvirgo8@nyu.edu', 'Female', '0154 Helena Lane', '154-312-3292');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (10, 'Agretha', 'Jesse', 'ajesse9@elpais.com', 'Female', '51 Welch Center', '363-160-9663');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (11, 'Kin', 'Gianotti', 'kgianottia@a8.net', 'Female', '176 Beilfuss Road', '736-506-4618');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (12, 'Morrie', 'Bickerdicke', 'mbickerdickeb@ezinearticles.com', 'Female', '0 Truax Place', '981-972-5860');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (13, 'Reginald', 'Sandey', 'rsandeyc@plala.or.jp', 'Female', '9 Lotheville Way', '657-316-8229');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (14, 'Kimball', 'Reggler', 'kregglerd@amazonaws.com', 'Female', '3201 Reindahl Way', '870-631-4179');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (15, 'Meghan', 'McCaw', 'mmccawe@jugem.jp', 'Male', '69238 Mayer Drive', '959-766-3759');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (16, 'Townsend', 'Allward', 'tallwardf@yale.edu', 'Female', '0 Eastwood Lane', '543-482-7067');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (17, 'Shea', 'Daal', 'sdaalg@bloglovin.com', 'Female', '99 Gerald Parkway', '529-526-9454');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (18, 'Ardyth', 'Brayn', 'abraynh@zimbio.com', 'Female', '04446 Bultman Alley', '454-444-3033');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (19, 'Justis', 'Shoulder', 'jshoulderi@alibaba.com', 'Female', '9 Butterfield Place', '366-165-4966');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (20, 'Gracia', 'Pennyman', 'gpennymanj@japanpost.jp', 'Male', '48 Veith Way', '230-575-6319');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (21, 'Walton', 'Heys', 'wheysk@wikia.com', 'Female', '98477 East Alley', '571-300-9131');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (22, 'Carver', 'Burburough', 'cburburoughl@google.ca', 'Female', '71953 Corscot Court', '489-367-1385');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (23, 'Bernadina', 'Gravells', 'bgravellsm@goo.ne.jp', 'Female', '79441 Kenwood Street', '833-822-2307');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (24, 'Carlynne', 'Hellewell', 'chellewelln@cornell.edu', 'Female', '1532 Nobel Drive', '615-424-4460');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (25, 'Pamela', 'Breawood', 'pbreawoodo@noaa.gov', 'Male', '735 1st Terrace', '344-646-3998');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (26, 'Damon', 'Mellmoth', 'dmellmothp@auda.org.au', 'Female', '6 Lake View Center', '136-544-1128');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (27, 'Tamarra', 'Neame', 'tneameq@cdc.gov', 'Female', '0 Sherman Point', '829-217-1680');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (28, 'Filippa', 'Vasile', 'fvasiler@engadget.com', 'Female', '7 Dahle Circle', '289-715-6265');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (29, 'Raf', 'Squire', 'rsquires@macromedia.com', 'Female', '21 East Pass', '604-407-0101');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (30, 'Annabela', 'Khadir', 'akhadirt@ed.gov', 'Female', '4199 Bellgrove Trail', '310-189-0580');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (31, 'Jenna', 'Jupp', 'jjuppu@comsenz.com', 'Female', '28762 Ronald Regan Center', '748-820-3630');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (32, 'Ivonne', 'Rispen', 'irispenv@scribd.com', 'Male', '21854 Morrow Terrace', '171-574-1095');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (33, 'Vinny', 'Casarino', 'vcasarinow@rambler.ru', 'Male', '9439 Artisan Lane', '101-591-4879');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (34, 'Teddy', 'Iacomelli', 'tiacomellix@narod.ru', 'Female', '00 Westport Park', '834-625-9212');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (35, 'Suzann', 'Fettis', 'sfettisy@myspace.com', 'Female', '0 Superior Park', '134-439-0034');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (36, 'Benny', 'Whitmarsh', 'bwhitmarshz@mediafire.com', 'Female', '67 Vahlen Crossing', '436-360-4043');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (37, 'Velvet', 'Clutheram', 'vclutheram10@ycombinator.com', 'Female', '71373 Spenser Hill', '567-962-7844');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (38, 'Delila', 'Luck', 'dluck11@soup.io', 'Female', '27 8th Alley', '398-252-6463');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (39, 'Emanuele', 'Fearn', 'efearn12@squarespace.com', 'Male', '6129 Ronald Regan Terrace', '821-710-5546');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (40, 'Christiane', 'Velasquez', 'cvelasquez13@ucoz.com', 'Male', '7 Glacier Hill Avenue', '705-760-4001');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (41, 'Ambrose', 'Pawley', 'apawley14@ow.ly', 'Female', '79 Johnson Place', '180-965-1970');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (42, 'Gray', 'Tortis', 'gtortis15@weibo.com', 'Male', '08455 Spaight Road', '757-692-2141');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (43, 'Fan', 'Doumerque', 'fdoumerque16@cargocollective.com', 'Female', '827 Debs Plaza', '163-258-9657');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (44, 'Carmencita', 'Jaquiss', 'cjaquiss17@eepurl.com', 'Male', '152 Shopko Crossing', '289-408-8702');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (45, 'Joelynn', 'Chipchase', 'jchipchase18@craigslist.org', 'Male', '64 Brickson Park Lane', '229-761-7182');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (46, 'Alexia', 'Thow', 'athow19@goo.ne.jp', 'Female', '778 Erie Trail', '956-343-9163');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (47, 'Britte', 'D''Agostino', 'bdagostino1a@wisc.edu', 'Male', '05827 Jay Plaza', '991-814-4778');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (48, 'Gun', 'McGriele', 'gmcgriele1b@dailymotion.com', 'Female', '19 Loeprich Pass', '323-597-3465');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (49, 'Ode', 'Scanlan', 'oscanlan1c@chronoengine.com', 'Female', '42 Iowa Alley', '780-314-7322');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (50, 'Abbe', 'Bothram', 'abothram1d@nsw.gov.au', 'Female', '4 Utah Terrace', '249-330-9412');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (51, 'Brett', 'Tebbut', 'btebbut1e@nymag.com', 'Male', '32 Talisman Junction', '867-555-3946');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (52, 'Tarrance', 'Elie', 'telie1f@amazonaws.com', 'Male', '69390 Welch Circle', '528-116-8505');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (53, 'Daria', 'Wimes', 'dwimes1g@homestead.com', 'Female', '48390 5th Center', '720-426-4874');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (54, 'Tersina', 'Chilles', 'tchilles1h@wikispaces.com', 'Female', '8 Waxwing Point', '408-723-8335');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (55, 'Hazlett', 'Lawty', 'hlawty1i@homestead.com', 'Male', '7728 Charing Cross Terrace', '144-789-2461');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (56, 'Lorette', 'Dixson', 'ldixson1j@google.it', 'Male', '498 Linden Road', '221-177-3986');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (57, 'Jeane', 'Dickson', 'jdickson1k@ucsd.edu', 'Male', '47 Messerschmidt Way', '174-868-0023');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (58, 'Danie', 'Gilbank', 'dgilbank1l@mysql.com', 'Female', '19 Buena Vista Hill', '988-617-2959');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (59, 'Eal', 'De Mitris', 'edemitris1m@github.com', 'Male', '1 Scofield Trail', '349-719-5411');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (60, 'Danell', 'MacAnelley', 'dmacanelley1n@fda.gov', 'Male', '1128 Lerdahl Crossing', '762-190-6037');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (61, 'Leshia', 'Arnley', 'larnley1o@npr.org', 'Female', '3205 Riverside Crossing', '994-866-0371');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (62, 'Tommie', 'Torrejon', 'ttorrejon1p@360.cn', 'Male', '4291 Red Cloud Lane', '218-691-9626');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (63, 'Pepita', 'Rahl', 'prahl1q@goo.ne.jp', 'Female', '2239 Harbort Terrace', '528-675-9978');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (64, 'Wally', 'Udell', 'wudell1r@blogs.com', 'Male', '9496 Riverside Park', '100-542-3479');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (65, 'Hartley', 'Petken', 'hpetken1s@com.com', 'Male', '0 Springview Court', '565-166-3841');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (66, 'Farr', 'Bohea', 'fbohea1t@xing.com', 'Female', '0426 Eastwood Court', '425-359-7820');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (67, 'Lisabeth', 'McAllister', 'lmcallister1u@biglobe.ne.jp', 'Male', '3586 Waxwing Pass', '900-311-7395');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (68, 'Shane', 'Onians', 'sonians1v@posterous.com', 'Female', '97985 Straubel Point', '855-209-8286');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (69, 'Dillon', 'Pimblott', 'dpimblott1w@unc.edu', 'Male', '5 5th Terrace', '476-681-2512');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (70, 'Ame', 'Chart', 'achart1x@businessinsider.com', 'Female', '668 Vahlen Street', '810-516-7446');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (71, 'Miriam', 'Cawtheray', 'mcawtheray1y@marketwatch.com', 'Male', '8 American Ash Way', '649-196-3613');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (72, 'Pernell', 'Axtell', 'paxtell1z@umich.edu', 'Female', '70 Mockingbird Circle', '528-597-4272');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (73, 'Deina', 'Matterson', 'dmatterson20@1688.com', 'Male', '07 Westridge Point', '778-287-8416');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (74, 'Ardisj', 'Pardey', 'apardey21@ustream.tv', 'Female', '89 Heath Alley', '489-709-0007');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (75, 'Andeee', 'Dew', 'adew22@mysql.com', 'Female', '42 Ryan Parkway', '819-305-7079');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (76, 'Emilie', 'Gambrell', 'egambrell23@reddit.com', 'Male', '5301 Parkside Alley', '749-327-1198');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (77, 'Frasier', 'Rose', 'frose24@sogou.com', 'Male', '2 Farragut Crossing', '842-703-0124');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (78, 'Emanuel', 'Dominighi', 'edominighi25@who.int', 'Male', '30502 Caliangt Center', '191-974-2976');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (79, 'Guido', 'Coutts', 'gcoutts26@archive.org', 'Male', '831 Sherman Court', '875-321-5540');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (80, 'Waiter', 'Swenson', 'wswenson27@biblegateway.com', 'Male', '4335 Onsgard Pass', '812-388-4862');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (81, 'Bryanty', 'Kendrew', 'bkendrew28@google.com.br', 'Female', '1909 Nevada Terrace', '347-270-3942');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (82, 'Jillayne', 'Misselbrook', 'jmisselbrook29@last.fm', 'Male', '818 Pierstorff Crossing', '299-281-9243');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (83, 'Lance', 'Marchiso', 'lmarchiso2a@google.fr', 'Male', '499 Jenna Terrace', '330-219-0118');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (84, 'Nerty', 'Tindley', 'ntindley2b@youtu.be', 'Female', '20603 Carey Avenue', '792-732-4041');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (85, 'Homer', 'Skayman', 'hskayman2c@nih.gov', 'Female', '10 Esker Trail', '334-210-0979');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (86, 'Rozalin', 'Spilstead', 'rspilstead2d@cpanel.net', 'Male', '152 Dwight Parkway', '936-884-7523');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (87, 'Cleopatra', 'Adamczewski', 'cadamczewski2e@51.la', 'Female', '933 Melvin Center', '224-130-9389');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (88, 'Yancy', 'Snelson', 'ysnelson2f@163.com', 'Female', '411 Chive Parkway', '206-328-8625');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (89, 'Abram', 'Manchett', 'amanchett2g@statcounter.com', 'Female', '13688 Loeprich Avenue', '736-724-5216');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (90, 'Archibald', 'Swindon', 'aswindon2h@scribd.com', 'Female', '983 Northfield Parkway', '349-840-1302');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (91, 'Cord', 'Scarbarrow', 'cscarbarrow2i@imdb.com', 'Female', '88997 Hintze Crossing', '950-453-5428');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (92, 'Chris', 'Lambrick', 'clambrick2j@home.pl', 'Female', '20 Porter Parkway', '118-121-5022');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (93, 'Alli', 'Rozier', 'arozier2k@jugem.jp', 'Male', '8 Portage Lane', '227-798-7760');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (94, 'Kaleb', 'Djakovic', 'kdjakovic2l@engadget.com', 'Male', '115 Eagle Crest Hill', '826-429-3004');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (95, 'Harriott', 'Jansens', 'hjansens2m@e-recht24.de', 'Male', '2713 Farmco Avenue', '577-584-0431');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (96, 'Mollee', 'Indruch', 'mindruch2n@drupal.org', 'Female', '727 Monument Pass', '616-294-8459');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (97, 'Nolie', 'Lowten', 'nlowten2o@123-reg.co.uk', 'Female', '0 Raven Parkway', '866-382-6534');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (98, 'Osborn', 'Coltan', 'ocoltan2p@ft.com', 'Female', '374 Center Pass', '656-827-5571');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (99, 'Berke', 'Deville', 'bdeville2q@mozilla.com', 'Male', '95 Dexter Alley', '288-876-8766');
insert into employee (id_employee, first_name, last_name, email, gender, address, phone) values (100, 'Georges', 'Folley', 'gfolley2r@noaa.gov', 'Female', '93648 Tomscot Avenue', '861-259-2437');
